# Generated by Django 4.2.6 on 2023-10-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Пости'},
        ),
    ]
